#!/bin/sh

LICENSE_ACCEPTED_PATH="${HOME}/.digitizer-license-accepted"
LICENSE_FILE=$SNAP'/usr/share/makerware/License.txt'

unset ACCEPTED

if [ -e ${LICENSE_ACCEPTED_PATH} ] ; then ACCEPTED=1; fi

if [ ! ${ACCEPTED} ] ; then
    zenity --text-info --title License --checkbox 'I read and accept the terms.' --filename ${LICENSE_FILE} && export ACCEPTED=1
    if [ ${ACCEPTED} ] ; then
	# We'll write the hash of the license file
	md5sum < ${LICENSE_FILE} > ${LICENSE_ACCEPTED_PATH}
	touch ${LICENSE_ACCEPTED_PATH}
    else
	echo "License declined; MakerWare will not run."
	exit 1
    fi
fi

if [ ${ACCEPTED} ] ; then
#this check is no longer needed see jira ticket 3589 for details 
   #if [ `lsb_release -s -c` = 'oneiric' ] ; then
#	export LD_LIBRARY_PATH="/usr/lib/makerbot${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
#    fi
    PULSELIB=`find $SNAP/usr/lib -name 'libpulsecommon*.so'`
    PULSELIBPATH=`dirname $PULSELIB`
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PULSELIBPATH
    $SNAP/usr/share/makerbot/digitizer_ui "$@"
fi
